PyTorch Fundamentals:

Table of Contents
* What are Tensors?
* Tensor Initialization
* Common Tensor Initialization Methods
* Tensor Type Conversion
* Converting Between NumPy Arrays and Tensors
* Tensor Mathematics and Comparison Operations
* Matrix Multiplication and Batch Operations
* Broadcasting and Other Useful Operations
* Tensor Indexing
* Tensor Reshaping


In [1]:
import torch
import numpy as np
# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

# Print versions
print("torch version:", torch.__version__)
print("numpy version:", np.__version__)

torch version: 2.7.1+cu118
numpy version: 2.4.2


What are Tensors?

Tensor holds a multi-dimensional array of elements of a single data type which is very similar with numpy’s ndarray. When the dimension is zero, it can be called a scalar. When the dimension is 1, it can be called a vector. When the dimension is 2, it can be called a matrix.

* 0-dimensional tensor: A single number (scalar).
* 1-dimensional tensor: A list of numbers (vector).
* 2-dimensional tensor: A table of numbers (matrix).

When the dimension is greater than 2, it is usually called a tensor.

Tensor Initialization

This code creates a 2×3 PyTorch tensor with float32 data type, assigns it to a specified device (CPU or GPU), and enables gradient tracking for backpropagation.

In [4]:
# Check for CUDA availability and set the device
device = "cuda" if torch.cuda.is_available() else "cpu"

# Initialize a 2x3 tensor with requires_grad enabled
my_tensor = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32, device=device, requires_grad= True)

print(my_tensor)
print("Data type:", my_tensor.dtype)
print("Device:", my_tensor.device)
print("Shape:", my_tensor.shape)
print("Requires Gradient:", my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
Data type: torch.float32
Device: cuda:0
Shape: torch.Size([2, 3])
Requires Gradient: True


Other Common Tensor Initialization Methods

* **Empty Tensor**: Creates an uninitialized 3×3 tensor (random values).
* **Zeros Tensor**: Creates a 3×3 tensor filled with zeros.
* **Random Tensor**: Generates a 3×3 tensor with random values between 0 and 1.
* **Ones Tensor**: Creates a 3×3 tensor filled with ones.
* **Identity Matrix**: Generates a 4×4 identity matrix (diagonal of ones).
* **Arange Tensor**: Creates a 1D tensor with values from 0 to 4 (step of 1).
* **Linspace Tensor**: Generates 5 evenly spaced values between 0.1 and 1.
* **Normal Distributed Tensor**: Fills a tensor with values from a normal (Gaussian) distribution with mean 0 and std 1.
* **Uniform Distributed Tensor**: Fills a tensor with values from a uniform distribution between 0 and 1.
* **Diagonal Tensor**: Creates a 4×4 diagonal tensor with ones along the diagonal and zeros elsewhere.

In [27]:
# Create an empty tensor of size 3x3
x = torch.empty(3, 3)
print("Empty Tensor:\n", x)

# Create a tensor filled with zeros
x = torch.zeros(3, 3)
print("Zeros Tensor:\n", x)

# Create a tensor with random values
x = torch.rand(3, 3)
print("Random Tensor:\n", x)

# Create a tensor filled with ones
x = torch.ones(3, 3)
print("Ones Tensor:\n", x)

# Create an identity matrix
x = torch.eye(4, 4)
print("Identity Matrix:\n", x)

# Create a tensor using arange
x = torch.arange(5)
print("Arange Tensor:\n", x)

# Create a tensor using linspace
x = torch.linspace(0.1, 1, 5)   
print("Linspace Tensor:\n", x)
#0.1 → start value
#1 → end value
#5 → number of points



Empty Tensor:
 tensor([[0.4955, 0.0260, 0.9778],
        [0.7489, 0.6070, 0.7928],
        [0.2546, 0.2416, 0.3667]])
Zeros Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Random Tensor:
 tensor([[0.3312, 0.6386, 0.8063],
        [0.8655, 0.9493, 0.1096],
        [0.8985, 0.2203, 0.3317]])
Ones Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Identity Matrix:
 tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
Arange Tensor:
 tensor([0, 1, 2, 3, 4])
Linspace Tensor:
 tensor([0.1000, 0.3250, 0.5500, 0.7750, 1.0000])


In [ ]:
# Create a tensor with values drawn from a normal distribution
x = torch.empty(1, 5).normal_(mean=0, std=1) #Creates a tensor with shape (1, 5) 1 row 5 colums
print("Normal Distributed Tensor:\n", x)

# Create a tensor with values drawn from a uniform distribution
x = torch.empty(1, 5).uniform_(0, 1)
print("Uniform Distributed Tensor:\n", x)

# Create a diagonal tensor from a tensor of ones
x = torch.diag(torch.ones(4))
print("Diagonal Tensor:\n", x)

Normal Distributed Tensor:
 tensor([[-0.1658,  1.1062, -1.3457,  0.2486,  0.5213]])
Uniform Distributed Tensor:
 tensor([[0.5023, 0.7729, 0.3463, 0.5365, 0.8676]])
Diagonal Tensor:
 tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


**Tensor Type Conversion**

Creates a tensor with values [0, 1, 2, 3] and demonstrates type conversion to boolean, int16, int64, float16, float32, and float64.

In [34]:
# Create a tensor and convert its type
tensor = torch.arange(4)
print("Boolean Tensor:", tensor.bool())   # Convert to boolean
print("Short Tensor (int16):", tensor.short())   # Convert to int16
print("Long Tensor (int64):", tensor.long())   # Convert to int64
print("Half Tensor (float16):", tensor.half())   # Convert to float16
print("Float Tensor (float32):", tensor.float())   # Convert to float32
print("Double Tensor (float64):", tensor.double())   # Convert to float64

Boolean Tensor: tensor([False,  True,  True,  True])
Short Tensor (int16): tensor([0, 1, 2, 3], dtype=torch.int16)
Long Tensor (int64): tensor([0, 1, 2, 3])
Half Tensor (float16): tensor([0., 1., 2., 3.], dtype=torch.float16)
Float Tensor (float32): tensor([0., 1., 2., 3.])
Double Tensor (float64): tensor([0., 1., 2., 3.], dtype=torch.float64)


**Converting Between NumPy Arrays and Tensors**

PyTorch makes it easy to switch between NumPy arrays and tensors, allowing seamless integration with existing computing workflows.

In [44]:

# Create a NumPy array of zeros
np_array = np.zeros((5, 5))
print("NumPy Array:\n", np_array)
print("===========================")

# Convert NumPy array to PyTorch tensor
tensor = torch.from_numpy(np_array)
print("Tensor from NumPy Array:\n", tensor)
print("=============================================")

# Convert tensor back to NumPy array
numpy_back = tensor.numpy()
print("Converted Back to NumPy Array:\n", numpy_back)


NumPy Array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Tensor from NumPy Array:
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
Converted Back to NumPy Array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


**Tensor Mathematics and Comparison Operations**

This section explores essential math operations with PyTorch tensors.

* **Addition & Subtraction**: Adds and subtracts two tensors element-wise.
* **Division**: Uses true division for precise results.
* **Inplace Operations**: Modifies a tensor directly without creating a new one.
* **Exponentiation**: Raises each element to a power using pow() or **.
* **Comparisons**: Checks conditions like x > 0 or x < 0, returning boolean results.
* **Dot Product**: Computes the sum of element-wise multiplications between two tensors.

In [50]:
# Define two tensors for operations
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

# Addition
z = x + y
print("Addition Results:", z)

# Addition using .add
z1 = torch.empty(3)
torch.add(x, y, out=z1)
z2 = torch.add(x, y)
print("Addition Results:", z, z1, z2)

# Subtraction
z = x - y
print("Subtraction Result:", z)

# Division (true division)
z = torch.true_divide(x, y)
print("Division Result:", z)

Addition Results: tensor([10, 10, 10])
Addition Results: tensor([10, 10, 10]) tensor([10., 10., 10.]) tensor([10, 10, 10])
Subtraction Result: tensor([-8, -6, -4])
Division Result: tensor([0.1111, 0.2500, 0.4286])


In [51]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

# Inplace operations
t = torch.ones(3)
print("Before inplace addition:", t)
t.add_(x)
print("After inplace addition:", t)
t += x  # Another inplace addition (note: t = t + x creates a new tensor)
print("After second inplace addition:", t)

Before inplace addition: tensor([1., 1., 1.])
After inplace addition: tensor([2., 3., 4.])
After second inplace addition: tensor([3., 5., 7.])


In [52]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

# Exponentiation
z = x.pow(2)
print("Exponentiation (pow):", z)
z = x**2
print("Exponentiation (**):", z)

# Comparisons
z = x > 0
print("x > 0:", z)
z = x < 0
print("x < 0:", z)

# Dot product
z = torch.dot(x, y)
print("Dot Product:", z)

Exponentiation (pow): tensor([1, 4, 9])
Exponentiation (**): tensor([1, 4, 9])
x > 0: tensor([True, True, True])
x < 0: tensor([False, False, False])
Dot Product: tensor(46)


**Matrix Multiplication and Batch Operations**

Matrix operations are at the heart of deep learning. Let's find out different ways to perform multiplication.

* **Matrix Multiplication**: Uses @ or torch.mm() to perform standard matrix multiplication.
* **Matrix Exponentiation**: Raises a square matrix to a power using matrix_power(n).
* **Element-wise Multiplication**: Uses torch.mul() or * for element-wise multiplication.
* **Batch Matrix Multiplication**: Uses torch.bmm() to multiply batches of matrices efficiently.

In [53]:
# Matrix multiplication using @ operator and torch.mm
x1 = torch.tensor([[1,2,3]])
y1 = torch.tensor([[9,8,7]])

z1 = x1 @ torch.t(y1)
print("Matrix Multiplication (@ operator):\n", z1)

z2 = torch.mm(x1, torch.t(y1))
print("Matrix Multiplication (torch.mm):\n", z2)

z3 = x1.mm(torch.t(y1))
print("Matrix Multiplication (mm):\n", z3)


Matrix Multiplication (@ operator):
 tensor([[46]])
Matrix Multiplication (torch.mm):
 tensor([[46]])
Matrix Multiplication (mm):
 tensor([[46]])


In [54]:
# Matrix exponentiation: multiplying a matrix with itself 3 times
matrix_exp = torch.rand(5, 5)
print("Matrix multiplied 3 times:\n", matrix_exp @ matrix_exp @ matrix_exp)
print("Matrix power 3:\n", matrix_exp.matrix_power(3))

Matrix multiplied 3 times:
 tensor([[5.1066, 2.7298, 2.9241, 4.2118, 5.4057],
        [3.0248, 1.6077, 1.9660, 2.7554, 3.0637],
        [3.1781, 1.3168, 2.3648, 2.9787, 3.4035],
        [2.7483, 1.5789, 1.8295, 2.6204, 2.7048],
        [3.0787, 1.4137, 2.0732, 2.6621, 3.2846]])
Matrix power 3:
 tensor([[5.1066, 2.7298, 2.9241, 4.2118, 5.4057],
        [3.0248, 1.6077, 1.9660, 2.7554, 3.0637],
        [3.1781, 1.3168, 2.3648, 2.9787, 3.4035],
        [2.7483, 1.5789, 1.8295, 2.6204, 2.7048],
        [3.0787, 1.4137, 2.0732, 2.6621, 3.2846]])


In [55]:
# Element-wise multiplication
z = torch.mul(x, y)
print("Element-wise Multiplication:", z)
z = x * y
print("Element-wise Multiplication (alternative):", z)

Element-wise Multiplication: tensor([ 9, 16, 21])
Element-wise Multiplication (alternative): tensor([ 9, 16, 21])


In [56]:
#batch matrix multiplication 
batch = 32
n, m, p = 10, 20, 30
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2) # Result shape: (batch, n, p)
print("Batch Matrix Multiplication (first batch):\n", out_bmm[0])
print("Shape of batched multiplication result:", (tensor1 @ tensor2).shape)


Batch Matrix Multiplication (first batch):
 tensor([[5.4793, 5.9816, 6.3348, 4.3154, 5.4277, 3.8108, 5.7077, 5.8273, 4.5317,
         4.4504, 4.0197, 5.7696, 5.9393, 4.0413, 5.9171, 4.9863, 3.7373, 5.5300,
         5.1520, 4.6475, 4.9934, 6.8230, 6.2570, 4.4887, 4.5905, 5.2680, 4.9713,
         4.4696, 5.1365, 5.0781],
        [5.7638, 5.7210, 6.6649, 4.8301, 5.9449, 4.2283, 5.1103, 6.1616, 4.8963,
         4.7344, 3.9982, 5.4366, 6.8428, 5.0743, 4.6415, 5.4759, 3.3979, 5.3900,
         4.6800, 4.8201, 4.2471, 6.2689, 6.5088, 3.9637, 4.1037, 5.7069, 4.8418,
         4.4881, 5.1086, 5.4092],
        [6.6048, 6.6330, 7.2302, 4.9282, 6.0628, 4.1850, 6.0232, 6.1229, 5.0916,
         5.7978, 4.0560, 6.1898, 7.3910, 4.9427, 5.3144, 5.4486, 4.4371, 6.4894,
         5.5296, 5.6340, 5.8959, 6.6839, 6.3187, 5.2508, 5.1905, 6.0581, 5.1539,
         5.7349, 6.1195, 5.9917],
        [5.3023, 6.0224, 6.3843, 4.6033, 5.4102, 4.0835, 4.7843, 6.2164, 4.8309,
         4.3781, 4.2828, 6.1630, 6.4496, 4.7

**Broadcasting and Other Useful Operations**

Broadcasting allows arithmetic operations on tensors of different shapes. This section also demonstrates additional useful functions.

* **Broadcasting**: Automatically expands smaller tensors to match larger ones in operations.
* **Summation**: torch.sum(x, dim=0) computes sum along a specific dimension.
* **Min/Max Values**: torch.max() and torch.min() return the highest and lowest values along a dimension.
* **Absolute Values**: torch.abs(x) gets the element-wise absolute values.
* **Argmax/Argmin**: torch.argmax() and torch.argmin() return the index of max/min values.
* **Mean Calculation**: torch.mean(x.float(), dim=0) computes the mean (ensuring float dtype).
* **Element-wise Comparison**: torch.eq(x, y) checks equality between two tensors.
* **Sorting**: torch.sort(y, dim=0) sorts tensor elements and returns indices.
* **Clamping**: torch.clamp(x, min=0) restricts values within a range.
* **Boolean Operations**: torch.any(x_bool) checks if any value is True, torch.all(x_bool) checks if all are True

In [61]:
x

tensor([1, 2, 3])

In [57]:
# Broadcasting example
x1 = torch.rand(5, 5)
x2 = torch.rand(5)

print("Tensor x1:\n", x1)
print("Tensor x2:\n", x2)
print("x1 - x2:\n", x1 - x2)
print("x1 raised to the power of x2:\n", x1 ** x2)

Tensor x1:
 tensor([[0.8103, 0.5228, 0.3940, 0.9472, 0.7691],
        [0.7989, 0.4309, 0.9423, 0.9497, 0.9701],
        [0.1220, 0.3622, 0.0791, 0.8605, 0.6666],
        [0.6034, 0.2783, 0.0246, 0.5327, 0.8358],
        [0.3811, 0.9017, 0.9952, 0.4302, 0.3220]])
Tensor x2:
 tensor([0.0946, 0.0346, 0.9235, 0.9813, 0.5451])
x1 - x2:
 tensor([[ 0.7158,  0.4882, -0.5295, -0.0341,  0.2240],
        [ 0.7044,  0.3963,  0.0189, -0.0316,  0.4250],
        [ 0.0274,  0.3276, -0.8444, -0.1208,  0.1215],
        [ 0.5089,  0.2437, -0.8989, -0.4485,  0.2907],
        [ 0.2865,  0.8671,  0.0717, -0.5511, -0.2231]])
x1 raised to the power of x2:
 tensor([[0.9803, 0.9778, 0.4231, 0.9482, 0.8667],
        [0.9790, 0.9713, 0.9466, 0.9506, 0.9836],
        [0.8195, 0.9655, 0.0961, 0.8629, 0.8017],
        [0.9533, 0.9567, 0.0326, 0.5391, 0.9069],
        [0.9128, 0.9964, 0.9956, 0.4370, 0.5392]])


In [58]:
# Sum of tensor elements along dimension 0
sum_x = torch.sum(x, dim=0)
print("Sum along dimension 0:", sum_x)


Sum along dimension 0: tensor(6)


In [60]:
# Maximum and minimum values
value, indices = torch.max(x, dim=0)
print("Max value and index:", value, indices)

value, indices = torch.min(x, dim=0)
print("Min value and index:", value, indices)

Max value and index: tensor(3) tensor(2)
Min value and index: tensor(1) tensor(0)


In [62]:
# Other operations
print(x)
print("Absolute values:", torch.abs(x))
print("Argmax:", torch.argmax(x, dim=0))
print("Argmin:", torch.argmin(x, dim=0))
print("Mean (converted to float):", torch.mean(x.float(), dim=0))
print("Element-wise equality (x == y):", torch.eq(x, y))

tensor([1, 2, 3])
Absolute values: tensor([1, 2, 3])
Argmax: tensor(2)
Argmin: tensor(0)
Mean (converted to float): tensor(2.)
Element-wise equality (x == y): tensor([False, False, False])


In [63]:
# Sorting
print(y)
sorted_y, indices = torch.sort(y, dim=0, descending=False)
print("Sorted y and indices:", sorted_y, indices)

tensor([9, 8, 7])
Sorted y and indices: tensor([7, 8, 9]) tensor([2, 1, 0])


In [64]:
# Clamping values
print("Clamped x:", torch.clamp(x, min=0))

Clamped x: tensor([1, 2, 3])


In [65]:
# Boolean operations
x_bool = torch.tensor([1, 0, 1, 1, 1], dtype=torch.bool)
print("Any True:", torch.any(x_bool))
print("All True:", torch.all(x_bool))


Any True: tensor(True)
All True: tensor(False)


**Tensor Indexing**

Access and modify tensor elements using indexing, slicing, and advanced indexing.

* **Accessing Rows & Columns**: Use x[row, :] for a row and x[:, col] for a column.
* **Slicing**: x[row, start:end] extracts a portion of a row.
* **Modifying Elements**: Directly assign values using x[row, col] = value.
* **Fancy Indexing**: Use a list of indices to select multiple elements at once.
* **Conditional Indexing**: Extract elements using conditions like (x < 2) | (x > 8).
* **Finding Even Numbers**: Use x.remainder(2) == 0 to filter even values.
* **Conditional Selection with torch.where()**: Chooses values based on a condition.

In [ ]:
# Create a random tensor with shape (batch_size, features)
batch_size = 10 # working with 10 samples (rows) at once
features = 25  #Each sample has 25 features (columns)
x = torch.rand((batch_size, features))

#access the first row 
print("first row: \n", x[0, :])
#access the second column
print("second column: \n", x[:,1])


first row: 
 tensor([7.9347e-01, 5.1944e-01, 5.3577e-01, 9.2125e-01, 9.4916e-01, 9.8064e-01,
        2.0384e-01, 1.7099e-01, 9.6645e-01, 8.4495e-01, 3.4688e-01, 6.0044e-01,
        6.2898e-01, 4.6524e-02, 3.5090e-01, 2.3513e-01, 2.3118e-01, 4.6515e-04,
        1.6666e-01, 4.2575e-01, 7.9920e-01, 7.7151e-01, 6.9697e-01, 6.6127e-01,
        3.8849e-01])
second column: 
 tensor([0.5194, 0.8489, 0.5987, 0.1443, 0.1288, 0.2600, 0.2315, 0.5334, 0.4941,
        0.2477])


In [70]:
# Access the first 10 elements of the third row
print("First 10 elements of third row: \n" ,x[2, 0:10])

First 10 elements of third row: 
 tensor([0.5005, 0.5987, 0.1400, 0.3568, 0.9657, 0.4953, 0.6109, 0.5632, 0.1940,
        0.0593])


In [76]:
# Modify a specific element (set first element to 100)
x[0, 0] = 100
x[0, 0]

tensor(100.)

In [81]:
# Fancy indexing example
x1 = torch.arange(10)
indices = [2, 5, 8]
print("Fancy indexing :", x1[indices])


Fancy indexing : tensor([2, 5, 8])


In [79]:
# Advanced indexing: select elements based on a condition
x2 = torch.arange(10)
print(x2)
print("Elements where x2 < 2 or x2 > 8:", x2[(x2 < 2) | (x2 > 8)])
print("Even numbers in x2:", x2[x2.remainder(2) == 0])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Elements where x2 < 2 or x2 > 8: tensor([0, 1, 9])
Even numbers in x2: tensor([0, 2, 4, 6, 8])


In [82]:
# Using torch.where to select values based on a condition
print("Using torch.where:", torch.where(x2 > 5, x2, x2 * 2))

Using torch.where: tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])


**Tensor Reshaping**

Learn how to reshape tensors, concatenate them, and change the order of dimensions.

* **Reshape with view() & reshape()**: Change tensor shape without altering data.
* **Transpose & Flatten**: .t() transposes, .contiguous().view(-1) flattens.
* **Concatenation**: torch.cat([x1, x2], dim=0/1) merges tensors along rows/columns.
* **Flattening**: .view(-1) converts a tensor into a 1D array.
* **Batch Reshaping**: .view(batch, -1) keeps batch size while reshaping.
* **Permute Dimensions**: .permute(0, 2, 1) reorders dimensions efficiently.
* **Unsqueeze for New Dimensions**: .unsqueeze(dim) adds singleton dimensions.

In [83]:
# Reshape a tensor using view and reshape
x = torch.arange(9)
print(x)
x_3x3 = x.view(3, 3)
print("Reshaped to 3x3 using view:\n", x_3x3)
x_3x3 = x.reshape(3, 3)
print("Reshaped to 3x3 using reshape:\n", x_3x3)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
Reshaped to 3x3 using view:
 tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
Reshaped to 3x3 using reshape:
 tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [84]:
# Transpose and flatten the tensor
y = x_3x3.t()
print("Flattened transposed tensor:", y.contiguous().view(9))

Flattened transposed tensor: tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [85]:
# Concatenation example
x1 = torch.rand(2, 5)
x2 = torch.rand(2, 5)
print("Concatenated along dimension 0 (rows):", torch.cat([x1, x2], dim=0).shape)
print("Concatenated along dimension 1 (columns):",torch.cat([x1, x2], dim=1).shape)


Concatenated along dimension 0 (rows): torch.Size([4, 5])
Concatenated along dimension 1 (columns): torch.Size([2, 10])


In [86]:
# Flatten the tensor using view(-1)
z = x1.view(-1)
print("Flattened tensor shape:", z.shape)

Flattened tensor shape: torch.Size([10])


In [87]:
# Reshape with batch dimension
batch = 64
x = torch.rand(batch, 2, 5)
print("Reshaped to (batch, -1):", x.view(batch, -1).shape)

Reshaped to (batch, -1): torch.Size([64, 10])


In [89]:
# Permute dimensions
z = x.permute(0, 2, 1)
print("Permuted tensor shape:", z.shape)

Permuted tensor shape: torch.Size([64, 5, 2])


In [90]:
# Unsqueeze examples (adding new dimensions)
x = torch.arange(10)
print("Original x:", x)
print("x unsqueezed at dim 0:", x.unsqueeze(0).shape, x.unsqueeze(0))
print("x unsqueezed at dim 1:", x.unsqueeze(1).shape, x.unsqueeze(1))

Original x: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x unsqueezed at dim 0: torch.Size([1, 10]) tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
x unsqueezed at dim 1: torch.Size([10, 1]) tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
